/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Player } from '../../models/player';

export interface DeletePlayer$Params {
  id: number;
}

export function deletePlayer(http: HttpClient, rootUrl: string, params: DeletePlayer$Params, context?: HttpContext): Observable<StrictHttpResponse<Player>> {
  const rb = new RequestBuilder(rootUrl, deletePlayer.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Player>;
    })
  );
}

deletePlayer.PATH = '/api/v1/players/{id}';
