/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { PlayersService } from './services/players.service';
export { AuthenticationService } from './services/authentication.service';
