/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Role {
  creationDate?: string;
  id?: number;
  lastUpdate?: string;
  name?: string;
}
